import { Stock } from './types';

export const INITIAL_CASH = 1000000;

// Ather Energy is not a publicly listed company, so it has not been included.
export const MOCK_STOCKS: Stock[] = [
  { ticker: 'RELIANCE', name: 'Reliance Industries', industry: 'Conglomerate', price: 2850.50, change: 0, changePercent: 0 },
  { ticker: 'TCS', name: 'Tata Consultancy', industry: 'IT Services', price: 3855.75, change: 0, changePercent: 0 },
  { ticker: 'HDFCBANK', name: 'HDFC Bank', industry: 'Financial', price: 1680.30, change: 0, changePercent: 0 },
  { ticker: 'INFY', name: 'Infosys', industry: 'IT Services', price: 1625.10, change: 0, changePercent: 0 },
  { ticker: 'ICICIBANK', name: 'ICICI Bank', industry: 'Financial', price: 1105.90, change: 0, changePercent: 0 },
  { ticker: 'HINDUNILVR', name: 'Hindustan Unilever', industry: 'Consumer Goods', price: 2550.00, change: 0, changePercent: 0 },
  { ticker: 'SBIN', name: 'State Bank of India', industry: 'Financial', price: 830.65, change: 0, changePercent: 0 },
  { ticker: 'BHARTIARTL', name: 'Bharti Airtel', industry: 'Telecom', price: 1350.20, change: 0, changePercent: 0 },
  { ticker: 'ITC', name: 'ITC Limited', industry: 'Conglomerate', price: 435.40, change: 0, changePercent: 0 },
  { ticker: 'LT', name: 'Larsen & Toubro', industry: 'Infrastructure', price: 3600.00, change: 0, changePercent: 0 },
  { ticker: 'TATAELXSI', name: 'Tata Elxsi', industry: 'IT Services', price: 7100.00, change: 0, changePercent: 0 },
  { ticker: 'JSWSTEEL', name: 'JSW Steel', industry: 'Metals', price: 915.50, change: 0, changePercent: 0 },
  { ticker: 'KIRLOSELEC', name: 'Kirloskar Electric', industry: 'Engineering', price: 225.80, change: 0, changePercent: 0 },
  { ticker: 'INOXWIND', name: 'Inox Wind', industry: 'Energy', price: 145.20, change: 0, changePercent: 0 },
  { ticker: 'TATAMOTORS', name: 'Tata Motors', industry: 'Automotive', price: 975.30, change: 0, changePercent: 0 },
  { ticker: 'WIPRO', name: 'Wipro', industry: 'IT Services', price: 480.15, change: 0, changePercent: 0 },
  { ticker: 'ADANIENT', name: 'Adani Enterprises', industry: 'Conglomerate', price: 3200.70, change: 0, changePercent: 0 },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance', industry: 'Financial', price: 7200.40, change: 0, changePercent: 0 },
  { ticker: 'MARUTI', name: 'Maruti Suzuki', industry: 'Automotive', price: 12500.00, change: 0, changePercent: 0 },
  { ticker: 'SUNPHARMA', name: 'Sun Pharmaceutical', industry: 'Pharma', price: 1500.80, change: 0, changePercent: 0 },
  { ticker: 'TITAN', name: 'Titan Company', industry: 'Consumer Goods', price: 3550.25, change: 0, changePercent: 0 },
  { ticker: 'ASIANPAINT', name: 'Asian Paints', industry: 'Chemicals', price: 2900.60, change: 0, changePercent: 0 },
  { ticker: 'NESTLEIND', name: 'Nestle India', industry: 'Consumer Goods', price: 2530.00, change: 0, changePercent: 0 },
  { ticker: 'KOTAKBANK', name: 'Kotak Mahindra Bank', industry: 'Financial', price: 1750.90, change: 0, changePercent: 0 },
  { ticker: 'HCLTECH', name: 'HCL Technologies', industry: 'IT Services', price: 1440.50, change: 0, changePercent: 0 },
  { ticker: 'AXISBANK', name: 'Axis Bank', industry: 'Financial', price: 1150.75, change: 0, changePercent: 0 },
  { ticker: 'NTPC', name: 'NTPC Limited', industry: 'Power', price: 360.40, change: 0, changePercent: 0 },
  { ticker: 'M&M', name: 'Mahindra & Mahindra', industry: 'Automotive', price: 2800.00, change: 0, changePercent: 0 },
  { ticker: 'POWERGRID', name: 'Power Grid Corp', industry: 'Power', price: 325.10, change: 0, changePercent: 0 },
  { ticker: 'ULTRACEMCO', name: 'UltraTech Cement', industry: 'Construction', price: 10800.00, change: 0, changePercent: 0 },
  { ticker: 'TATASTEEL', name: 'Tata Steel', industry: 'Metals', price: 165.70, change: 0, changePercent: 0 },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank', industry: 'Financial', price: 1480.20, change: 0, changePercent: 0 },
  { ticker: 'TECHM', name: 'Tech Mahindra', industry: 'IT Services', price: 1300.00, change: 0, changePercent: 0 },
  { ticker: 'DRREDDY', name: "Dr. Reddy's Labs", industry: 'Pharma', price: 6200.50, change: 0, changePercent: 0 },
  { ticker: 'GRASIM', name: 'Grasim Industries', industry: 'Conglomerate', price: 2400.90, change: 0, changePercent: 0 },
  { ticker: 'ADANIPORTS', name: 'Adani Ports', industry: 'Infrastructure', price: 1350.30, change: 0, changePercent: 0 },
  { ticker: 'CIPLA', name: 'Cipla', industry: 'Pharma', price: 1490.00, change: 0, changePercent: 0 },
  { ticker: 'HINDALCO', name: 'Hindalco Industries', industry: 'Metals', price: 670.60, change: 0, changePercent: 0 },
  { ticker: 'EICHERMOT', name: 'Eicher Motors', industry: 'Automotive', price: 4700.80, change: 0, changePercent: 0 },
  { ticker: 'BRITANNIA', name: 'Britannia Industries', industry: 'Consumer Goods', price: 5300.20, change: 0, changePercent: 0 },
  { ticker: 'SBILIFE', name: 'SBI Life Insurance', industry: 'Insurance', price: 1450.40, change: 0, changePercent: 0 },
  { ticker: 'BPCL', name: 'Bharat Petroleum', industry: 'Oil & Gas', price: 305.00, change: 0, changePercent: 0 },
  { ticker: 'HEROMOTOCO', name: 'Hero MotoCorp', industry: 'Automotive', price: 5500.00, change: 0, changePercent: 0 },
  { ticker: 'DIVISLAB', name: "Divi's Laboratories", industry: 'Pharma', price: 4400.75, change: 0, changePercent: 0 },
  { ticker: 'TATACONSUM', name: 'Tata Consumer Products', industry: 'Consumer Goods', price: 1100.10, change: 0, changePercent: 0 },
  { ticker: 'ONGC', name: 'Oil & Natural Gas Corp', industry: 'Oil & Gas', price: 270.50, change: 0, changePercent: 0 },
  { ticker: 'APOLLOHOSP', name: 'Apollo Hospitals', industry: 'Healthcare', price: 6100.00, change: 0, changePercent: 0 },
  { ticker: 'LTIM', name: 'LTIMindtree', industry: 'IT Services', price: 5100.90, change: 0, changePercent: 0 },
  { ticker: 'ZOMATO', name: 'Zomato', industry: 'Platform', price: 185.30, change: 0, changePercent: 0 },
  { ticker: 'VEDL', name: 'Vedanta', industry: 'Metals', price: 450.60, change: 0, changePercent: 0 },
  { ticker: 'SIEMENS', name: 'Siemens', industry: 'Engineering', price: 7400.00, change: 0, changePercent: 0 },
];
